### ISSUE TITLE
plugin crash on clicking installed lexicon in lexicon repository

### ISSUE THREAD

**Issue by johnysandels** [karashiiro/TextToTalk#112]
```2022-05-01 22:25:22.539 -07:00 [INF] [TextToTalk] Fetching lexicon package list...
2022-05-01 22:25:24.355 -07:00 [ERR] [TextToTalk] UiBuilder OnBuildUi caught exception
System.Collections.Generic.KeyNotFoundException: The given key 'Uberduck' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TextToTalk.UI.Dalamud.Lexicons.LexiconRepositorySubwindow.DrawSelectedPackageSettings() in K:\arashiiro\UI\Dalamud\Lexicons\LexiconRepositorySubwindow.cs:line 189
   at TextToTalk.UI.Dalamud.Lexicons.LexiconRepositorySubwindow.Draw(Boolean& visible) in K:\arashiiro\UI\Dalamud\Lexicons\LexiconRepositorySubwindow.cs:line 56
   at TextToTalk.UI.Dalamud.Lexicons.LexiconComponent.Draw() in K:\arashiiro\UI\Dalamud\Lexicons\LexiconComponent.cs:line 46
   at TextToTalk.Backends.System.SystemBackendUI.DrawSettings(IConfigUIDelegates helpers) in K:\arashiiro\Backends\System\SystemBackendUI.cs:line 139
   at TextToTalk.UI.Dalamud.ConfigurationWindow.DrawSynthesizerSettings() in K:\arashiiro\UI\Dalamud\ConfigurationWindow.cs:line 209
   at TextToTalk.UI.Dalamud.ConfigurationWindow.Draw(Boolean& visible) in K:\arashiiro\UI\Dalamud\ConfigurationWindow.cs:line 44
   at Dalamud.CrystalTower.UI.WindowManager.Draw()
   ```

**Comment by karashiiro** [comment]
Fixed [v1.15.2](https://github.com/goatcorp/DalamudPlugins/pull/2479)
