### ISSUE TITLE
Stops working after logged out to the main screen. (Test version)

### ISSUE THREAD

**Issue by Myojine** [karashiiro/TextToTalk#39]
Title.

Getting logged out from the reintroduced anti-afk timer means you have to restart the game or disable>re-enable the plugin to get TTS back.

**Comment by karashiiro** [comment]
Do you have any errors in your log? This might be related to an issue where logging out spams your Dalamud logs with errors.

**Comment by johnysandels** [comment]
`2021-08-07 03:37:35.485 -04:00 [INF] [Dalamud] TTS enabled.
2021-08-07 03:37:41.705 -04:00 [INF] [ChatTranslator] PRED LANG: la
2021-08-07 03:37:41.754 -04:00 [INF] [ChatTranslator] FALSE so printChat
2021-08-07 03:37:41.769 -04:00 [INF] [ChatTranslator] Caught loop A
2021-08-07 03:37:41.769 -04:00 [ERR] Exception on OnChatMessage hook.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at ChatBubbles.ChatBubbles.Chat_OnChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& cmessage, Boolean& isHandled)
   at Dalamud.Game.Internal.Gui.ChatGui.OnMessageDelegate.Invoke(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled)
   at Dalamud.Game.Internal.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter) in C:\goatsoft\companysecrets\dalamud\Game\Internal\Gui\ChatGui.cs:line 391
2021-08-07 03:37:51.003 -04:00 [INF] [SimpleTweaksPlugin] Add ItemLevel to CharacterInspect
2021-08-07 03:38:26.056 -04:00 [INF] [Dalamud.LoadingImage] LoadIcon: 0 detected for r:1 with toLoadingTerri:129
2021-08-07 03:38:26.056 -04:00 [INF] [Dalamud.LoadingImage] Mismatch: 129 1
2021-08-07 03:38:26.463 -04:00 [INF] [SimpleTweaksPlugin] Rename Tab: 'Battle' -> 'Social' [47]
2021-08-07 03:38:26.463 -04:00 [INF] [SimpleTweaksPlugin] Rename Panel: 'Battle' -> ' Social'
2021-08-07 03:38:33.052 -04:00 [INF] [SonarPlugin] Fate manager address changed to 293658BEF60
2021-08-07 03:38:39.230 -04:00 [INF] [Dalamud] TTS disabled.
2021-08-07 03:38:39.680 -04:00 [INF] [Dalamud] TTS enabled.`

When first enabled the TTS plays. I log out and log back in, click on a NPC with dialogue, TTS doesn't work. Disable and enable TTS, and TTS still doesn't work.

**Comment by karashiiro** [comment]
Should be fixed in testing as of https://github.com/goatcorp/DalamudPlugins/pull/1103, let me know if it works.
