### ISSUE TITLE
sometimes it cuts off

### ISSUE THREAD

**Issue by Auncaughbove17** [karashiiro/TextToTalk#65]
The way I use this, is the following:
I have tts on and just skip through text of quests, and then listen to it while I'm doing the quest. This works great! But sometimes it cuts off the end of a sentence. Imagine the following example, where I speak to an NPC who says three sentences:

This is sentence one, I am reading this fully.
This is sentence two, I am [cuts off]
This is sentence three, I am reading this fully.

I am not sure what causes it. I don't think it overloads the queue or something since it keeps talking after the cut off section. Are there any logs I could provide, if that is necessary?

**Comment by karashiiro** [comment]
In the general settings, do you have "Cancel the current speech when new text is available or text is advanced" enabled?

**Comment by Auncaughbove17** [comment]
no, it is not. Else it cancels as soon as I press `A` and doesn't queue the speech at all.
The queueing *does* work and well, except that rarely, a sentence gets cut off.

**Comment by Auncaughbove17** [comment]
My dalamud.log file seems to be out of date? 
But I have a good example of where it cut out. Here are two images of the conversation logs. It's the MSQ quest right after ARR. The red rectangle shows the text that was skipped. All the rest was read!
<details>
<summary>Click to see the images</summary>

![ffxiv_dx11_NomjHKkluG](https://user-images.githubusercontent.com/26165288/147874474-9b6ce0e4-773f-4f96-a8a1-c89bc3e92810.png)
![ffxiv_dx11_IwIMd6Fm14](https://user-images.githubusercontent.com/26165288/147874475-8f1f7615-383d-4419-95ed-f4fd1765a917.png)
</details>

Regarding the dalamud.log, I did see an error in there which seems to point towards the use of Lexicons, so I will deactivate them for now to see if it fixes it, though the logs are about 2 hours behind, so I don't know if it is related. Here is the error from the log though, in case it is of note. I hope there is no sensitive data in there I'm not aware of...

<details>
<summary>Click to see the log</summary>

```log
2022-01-02 10:20:30.732 +01:00 [INF] [LOCALPLUGIN] Loading TextToTalk.dll
2022-01-02 10:20:31.858 +01:00 [INF] [LOCALPLUGIN] Finished loading TextToTalk.dll
2022-01-02 10:20:31.868 +01:00 [INF] TROUBLESHOOTING:eyJMb2FkZWRQbHVnaW5zIjpbeyJEaXNhYmxlZCI6ZmFsc2UsIlRlc3RpbmciOmZhbHNlLCJJbnN0YWxsZWRGcm9tVXJsIjpudWxsLCJJc1RoaXJkUGFydHkiOmZhbHNlLCJBdXRob3IiOiJrYXJhc2hpaXJvIiwiTmFtZSI6IlRleHRUb1RhbGsiLCJQdW5jaGxpbmUiOm51bGwsIkRlc2NyaXB0aW9uIjoiQ2hhdCBUVFMuIFVzZSAvdHR0Y29uZmlnIHRvIGNvbmZpZ3VyZSB0aGUgZW5hYmxlZCBjaGFubmVscyBhbmQgdHJpZ2dlcnMvZXhjZXB0aW9ucy4iLCJDaGFuZ2Vsb2ciOm51bGwsIlRhZ3MiOlsidHRzIiwidHJpZ2dlciIsInRyaWdnZXJzIiwidm9pY2UiLCJ2b2ljZXMiLCJzcGVlY2giLCJrYXJhc2hpaXJvIl0sIkNhdGVnb3J5VGFncyI6WyJVSSJdLCJJc0hpZGUiOmZhbHNlLCJJbnRlcm5hbE5hbWUiOiJUZXh0VG9UYWxrIiwiQXNzZW1ibHlWZXJzaW9uIjoiMS45LjEzLjAiLCJUZXN0aW5nQXNzZW1ibHlWZXJzaW9uIjoiMS45LjEyLjEiLCJJc1Rlc3RpbmdFeGNsdXNpdmUiOmZhbHNlLCJSZXBvVXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL2thcmFzaGlpcm8vVGV4dFRvVGFsayIsIkFwcGxpY2FibGVWZXJzaW9uIjoiYW55IiwiRGFsYW11ZEFwaUxldmVsIjo1LCJEb3dubG9hZENvdW50IjoxMDU5OSwiTGFzdFVwZGF0ZSI6MTY0MDY1OTYxOCwiRG93bmxvYWRMaW5rSW5zdGFsbCI6Imh0dHBzOi8vdXMtY2VudHJhbDEteGwtZnVuY3Rpb25zLmNsb3VkZnVuY3Rpb25zLm5ldC9kb3dubG9hZC1wbHVnaW4vP3BsdWdpbj1UZXh0VG9UYWxrJmlzVXBkYXRlPUZhbHNlJmlzVGVzdGluZz1GYWxzZSZicmFuY2g9YXBpNSIsIkRvd25sb2FkTGlua1VwZGF0ZSI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9nb2F0Y29ycC9EYWxhbXVkUGx1Z2lucy9hcGk1L3BsdWdpbnMvVGV4dFRvVGFsay9sYXRlc3QuemlwIiwiRG93bmxvYWRMaW5rVGVzdGluZyI6Imh0dHBzOi8vdXMtY2VudHJhbDEteGwtZnVuY3Rpb25zLmNsb3VkZnVuY3Rpb25zLm5ldC9kb3dubG9hZC1wbHVnaW4vP3BsdWdpbj1UZXh0VG9UYWxrJmlzVXBkYXRlPUZhbHNlJmlzVGVzdGluZz1UcnVlJmJyYW5jaD1hcGk1IiwiTG9hZFByaW9yaXR5IjowLCJJbWFnZVVybHMiOm51bGwsIkljb25VcmwiOm51bGwsIkFjY2VwdHNGZWVkYmFjayI6dHJ1ZSwiRmVlZGJhY2tNZXNzYWdlIjpudWxsLCJGZWVkYmFja1dlYmhvb2siOm51bGx9XSwiRGFsYW11ZFZlcnNpb24iOiI2LjIuMC4xNCIsIkRhbGFtdWRHaXRIYXNoIjoiMDIwMDQ2OCIsIkdhbWVWZXJzaW9uIjoiMjAyMS4xMi4xNi4wMDAwLjAwMDAiLCJMYW5ndWFnZSI6IkVuZ2xpc2giLCJEb0RhbGFtdWRUZXN0IjpmYWxzZSwiRG9QbHVnaW5UZXN0IjpmYWxzZSwiSW50ZXJmYWNlTG9hZGVkIjp0cnVlLCJGb3JjZWRNaW5Ib29rIjpmYWxzZSwiVGhpcmRSZXBvIjpbXX0=
2022-01-02 10:21:25.571 +01:00 [INF] [PLUGINM] Starting plugin update
2022-01-02 10:21:25.572 +01:00 [INF] TROUBLESHOOTING:eyJMb2FkZWRQbHVnaW5zIjpbeyJEaXNhYmxlZCI6ZmFsc2UsIlRlc3RpbmciOmZhbHNlLCJJbnN0YWxsZWRGcm9tVXJsIjpudWxsLCJJc1RoaXJkUGFydHkiOmZhbHNlLCJBdXRob3IiOiJrYXJhc2hpaXJvIiwiTmFtZSI6IlRleHRUb1RhbGsiLCJQdW5jaGxpbmUiOm51bGwsIkRlc2NyaXB0aW9uIjoiQ2hhdCBUVFMuIFVzZSAvdHR0Y29uZmlnIHRvIGNvbmZpZ3VyZSB0aGUgZW5hYmxlZCBjaGFubmVscyBhbmQgdHJpZ2dlcnMvZXhjZXB0aW9ucy4iLCJDaGFuZ2Vsb2ciOm51bGwsIlRhZ3MiOlsidHRzIiwidHJpZ2dlciIsInRyaWdnZXJzIiwidm9pY2UiLCJ2b2ljZXMiLCJzcGVlY2giLCJrYXJhc2hpaXJvIl0sIkNhdGVnb3J5VGFncyI6WyJVSSJdLCJJc0hpZGUiOmZhbHNlLCJJbnRlcm5hbE5hbWUiOiJUZXh0VG9UYWxrIiwiQXNzZW1ibHlWZXJzaW9uIjoiMS45LjEzLjAiLCJUZXN0aW5nQXNzZW1ibHlWZXJzaW9uIjoiMS45LjEyLjEiLCJJc1Rlc3RpbmdFeGNsdXNpdmUiOmZhbHNlLCJSZXBvVXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL2thcmFzaGlpcm8vVGV4dFRvVGFsayIsIkFwcGxpY2FibGVWZXJzaW9uIjoiYW55IiwiRGFsYW11ZEFwaUxldmVsIjo1LCJEb3dubG9hZENvdW50IjoxMDU5OSwiTGFzdFVwZGF0ZSI6MTY0MDY1OTYxOCwiRG93bmxvYWRMaW5rSW5zdGFsbCI6Imh0dHBzOi8vdXMtY2VudHJhbDEteGwtZnVuY3Rpb25zLmNsb3VkZnVuY3Rpb25zLm5ldC9kb3dubG9hZC1wbHVnaW4vP3BsdWdpbj1UZXh0VG9UYWxrJmlzVXBkYXRlPUZhbHNlJmlzVGVzdGluZz1GYWxzZSZicmFuY2g9YXBpNSIsIkRvd25sb2FkTGlua1VwZGF0ZSI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9nb2F0Y29ycC9EYWxhbXVkUGx1Z2lucy9hcGk1L3BsdWdpbnMvVGV4dFRvVGFsay9sYXRlc3QuemlwIiwiRG93bmxvYWRMaW5rVGVzdGluZyI6Imh0dHBzOi8vdXMtY2VudHJhbDEteGwtZnVuY3Rpb25zLmNsb3VkZnVuY3Rpb25zLm5ldC9kb3dubG9hZC1wbHVnaW4vP3BsdWdpbj1UZXh0VG9UYWxrJmlzVXBkYXRlPUZhbHNlJmlzVGVzdGluZz1UcnVlJmJyYW5jaD1hcGk1IiwiTG9hZFByaW9yaXR5IjowLCJJbWFnZVVybHMiOm51bGwsIkljb25VcmwiOm51bGwsIkFjY2VwdHNGZWVkYmFjayI6dHJ1ZSwiRmVlZGJhY2tNZXNzYWdlIjpudWxsLCJGZWVkYmFja1dlYmhvb2siOm51bGx9XSwiRGFsYW11ZFZlcnNpb24iOiI2LjIuMC4xNCIsIkRhbGFtdWRHaXRIYXNoIjoiMDIwMDQ2OCIsIkdhbWVWZXJzaW9uIjoiMjAyMS4xMi4xNi4wMDAwLjAwMDAiLCJMYW5ndWFnZSI6IkVuZ2xpc2giLCJEb0RhbGFtdWRUZXN0IjpmYWxzZSwiRG9QbHVnaW5UZXN0IjpmYWxzZSwiSW50ZXJmYWNlTG9hZGVkIjp0cnVlLCJGb3JjZWRNaW5Ib29rIjpmYWxzZSwiVGhpcmRSZXBvIjpbXX0=
2022-01-02 10:21:25.572 +01:00 [INF] [PLUGINM] Plugin update OK.
2022-01-02 10:22:06.504 +01:00 [ERR] [TextToTalk] Synthesis request failed in PollyClient.
Amazon.Polly.Model.LexiconNotFoundException: Lexicon not found
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at TextToTalk.Backends.Polly.PollyClient.Say(Engine engine, VoiceId voice, Int32 sampleRate, Single volume, IEnumerable`1 lexicons, TextSource source, String text) in K:\arashiiro\Backends\Polly\PollyClient.cs:line 112
2022-01-02 10:22:06.691 +01:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMS0wMlQxMDoyMjowNi42ODYzODUyKzAxOjAwIiwiSW5mbyI6IkFtYXpvbi5Qb2xseS5Nb2RlbC5MZXhpY29uTm90Rm91bmRFeGNlcHRpb246IExleGljb24gbm90IGZvdW5kXHJcbiAtLS0+IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkh0dHBFcnJvclJlc3BvbnNlRXhjZXB0aW9uOiBFeGNlcHRpb24gb2YgdHlwZSAnQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuSHR0cEVycm9yUmVzcG9uc2VFeGNlcHRpb24nIHdhcyB0aHJvd24uXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkh0dHBXZWJSZXF1ZXN0TWVzc2FnZS5HZXRSZXNwb25zZUFzeW5jKENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5IdHRwSGFuZGxlcmAxLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLlVubWFyc2hhbGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5FcnJvckhhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkh0dHBFcnJvclJlc3BvbnNlRXhjZXB0aW9uSGFuZGxlci5IYW5kbGVFeGNlcHRpb25TdHJlYW0oSVJlcXVlc3RDb250ZXh0IHJlcXVlc3RDb250ZXh0LCBJV2ViUmVzcG9uc2VEYXRhIGh0dHBFcnJvclJlc3BvbnNlLCBIdHRwRXJyb3JSZXNwb25zZUV4Y2VwdGlvbiBleGNlcHRpb24sIFN0cmVhbSByZXNwb25zZVN0cmVhbSlcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuSHR0cEVycm9yUmVzcG9uc2VFeGNlcHRpb25IYW5kbGVyLkhhbmRsZUV4Y2VwdGlvbkFzeW5jKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIEh0dHBFcnJvclJlc3BvbnNlRXhjZXB0aW9uIGV4Y2VwdGlvbilcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRXhjZXB0aW9uSGFuZGxlcmAxLkhhbmRsZUFzeW5jKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIEV4Y2VwdGlvbiBleGNlcHRpb24pXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkVycm9ySGFuZGxlci5Qcm9jZXNzRXhjZXB0aW9uQXN5bmMoSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dCwgRXhjZXB0aW9uIGV4Y2VwdGlvbilcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRXJyb3JIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkNhbGxiYWNrSGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5FbmRwb2ludERpc2NvdmVyeUhhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRW5kcG9pbnREaXNjb3ZlcnlIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkNyZWRlbnRpYWxzUmV0cmlldmVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLlJldHJ5SGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5SZXRyeUhhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuQ2FsbGJhY2tIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkNhbGxiYWNrSGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5FcnJvckNhbGxiYWNrSGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5NZXRyaWNzSGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBUZXh0VG9UYWxrLkJhY2tlbmRzLlBvbGx5LlBvbGx5Q2xpZW50LlNheShFbmdpbmUgZW5naW5lLCBWb2ljZUlkIHZvaWNlLCBJbnQzMiBzYW1wbGVSYXRlLCBTaW5nbGUgdm9sdW1lLCBJRW51bWVyYWJsZWAxIGxleGljb25zLCBUZXh0U291cmNlIHNvdXJjZSwgU3RyaW5nIHRleHQpIGluIEs6XFxhcmFzaGlpcm9cXEJhY2tlbmRzXFxQb2xseVxcUG9sbHlDbGllbnQuY3M6bGluZSAxMTIiLCJDb250ZXh0IjoiW1RleHRUb1RhbGtdIFN5bnRoZXNpcyByZXF1ZXN0IGZhaWxlZCBpbiBcIlBvbGx5Q2xpZW50XCIuXG5BbWF6b24uUG9sbHkuTW9kZWwuTGV4aWNvbk5vdEZvdW5kRXhjZXB0aW9uOiBMZXhpY29uIG5vdCBmb3VuZFxyXG4gLS0tPiBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5IdHRwRXJyb3JSZXNwb25zZUV4Y2VwdGlvbjogRXhjZXB0aW9uIG9mIHR5cGUgJ0FtYXpvbi5SdW50aW1lLkludGVybmFsLkh0dHBFcnJvclJlc3BvbnNlRXhjZXB0aW9uJyB3YXMgdGhyb3duLlxyXG4gICBhdCBBbWF6b24uUnVudGltZS5IdHRwV2ViUmVxdWVzdE1lc3NhZ2UuR2V0UmVzcG9uc2VBc3luYyhDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuSHR0cEhhbmRsZXJgMS5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5Vbm1hcnNoYWxsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRXJyb3JIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5IdHRwRXJyb3JSZXNwb25zZUV4Y2VwdGlvbkhhbmRsZXIuSGFuZGxlRXhjZXB0aW9uU3RyZWFtKElSZXF1ZXN0Q29udGV4dCByZXF1ZXN0Q29udGV4dCwgSVdlYlJlc3BvbnNlRGF0YSBodHRwRXJyb3JSZXNwb25zZSwgSHR0cEVycm9yUmVzcG9uc2VFeGNlcHRpb24gZXhjZXB0aW9uLCBTdHJlYW0gcmVzcG9uc2VTdHJlYW0pXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkh0dHBFcnJvclJlc3BvbnNlRXhjZXB0aW9uSGFuZGxlci5IYW5kbGVFeGNlcHRpb25Bc3luYyhJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0LCBIdHRwRXJyb3JSZXNwb25zZUV4Y2VwdGlvbiBleGNlcHRpb24pXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkV4Y2VwdGlvbkhhbmRsZXJgMS5IYW5kbGVBc3luYyhJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0LCBFeGNlcHRpb24gZXhjZXB0aW9uKVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5FcnJvckhhbmRsZXIuUHJvY2Vzc0V4Y2VwdGlvbkFzeW5jKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQsIEV4Y2VwdGlvbiBleGNlcHRpb24pXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkVycm9ySGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5DYWxsYmFja0hhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRW5kcG9pbnREaXNjb3ZlcnlIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkVuZHBvaW50RGlzY292ZXJ5SGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5DcmVkZW50aWFsc1JldHJpZXZlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5SZXRyeUhhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuUmV0cnlIYW5kbGVyLkludm9rZUFzeW5jW1RdKElFeGVjdXRpb25Db250ZXh0IGV4ZWN1dGlvbkNvbnRleHQpXHJcbiAgIGF0IEFtYXpvbi5SdW50aW1lLkludGVybmFsLkNhbGxiYWNrSGFuZGxlci5JbnZva2VBc3luY1tUXShJRXhlY3V0aW9uQ29udGV4dCBleGVjdXRpb25Db250ZXh0KVxyXG4gICBhdCBBbWF6b24uUnVudGltZS5JbnRlcm5hbC5DYWxsYmFja0hhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuRXJyb3JDYWxsYmFja0hhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgQW1hem9uLlJ1bnRpbWUuSW50ZXJuYWwuTWV0cmljc0hhbmRsZXIuSW52b2tlQXN5bmNbVF0oSUV4ZWN1dGlvbkNvbnRleHQgZXhlY3V0aW9uQ29udGV4dClcclxuICAgYXQgVGV4dFRvVGFsay5CYWNrZW5kcy5Qb2xseS5Qb2xseUNsaWVudC5TYXkoRW5naW5lIGVuZ2luZSwgVm9pY2VJZCB2b2ljZSwgSW50MzIgc2FtcGxlUmF0ZSwgU2luZ2xlIHZvbHVtZSwgSUVudW1lcmFibGVgMSBsZXhpY29ucywgVGV4dFNvdXJjZSBzb3VyY2UsIFN0cmluZyB0ZXh0KSBpbiBLOlxcYXJhc2hpaXJvXFxCYWNrZW5kc1xcUG9sbHlcXFBvbGx5Q2xpZW50LmNzOmxpbmUgMTEyIn0=
```
</details>

**Comment by karashiiro** [comment]
I just merged a fix for that specific exception, still not sure about the general issue with things cutting off, though: https://github.com/goatcorp/DalamudPlugins/pull/1823

**Comment by johnysandels** [comment]
I do know that having _Read from Dialogue box_ and having NPC Dialogue channel selected in the channel settings can cause some issues. I would suggest, only having one enabled, and see if that causes any issues. (reading from the chat NPC Dialogue channel will only read the message after you've clicked to close the current chat box, so I suggest disabling that one if you have both enabled.)
